apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: mysql
type: Opaque
stringData:
  mysql-root-password: "MyS3cureR00tP@ss!"
  mysql-password: "MyS3cureAppP@ss!"
  mysql-replication-password: "MyS3cureR3plP@ss!"