apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-app
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: "21.1.23"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: nginx-app.example.com
      pathType: ImplementationSpecific
      annotations:
        kubernetes.io/ingress.class: "nginx"
      tls: []