apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    externalDatabase:
      existingSecret: mysql-auth   # use MySQL secret directly
      userKey: username
      passwordKey: mysql-password
      databaseKey: database
      host: mysql                  # ExternalName service in WordPress namespace
      port: 3306

    mariadb:
      enabled: false               # disable built-in MariaDB

    existingSecret: wordpress-admin
    existingSecretUsernameKey: wordpress-username
    existingSecretPasswordKey: wordpress-password

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wordpress.example.com
      pathType: ImplementationSpecific
      annotations:
        kubernetes.io/ingress.class: "nginx"
      tls: false
