apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    existingSecret: wordpress-admin
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.mysql-ns.svc.cluster.local
      port: 3306
      user: appuser
      database: wordpress
      existingSecret: mysql-auth
      existingSecretPasswordKey: mysql-password
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wordpress.local
      pathType: Prefix
      annotations: {}
      tls: []
