apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:ZKXCV2b69Q==,iv:GBkeb8Vw2tOSlf6CWXwd/gXHDZy1JAeUTZ+GSrG6OC8=,tag:0sCVqAGFDM9+BqFesXCVSg==,type:str]
    db-password: ENC[AES256_GCM,data:twFxYLfQUVQXs+TJx3V/Qg==,iv:BzWRzpztpTaFoZkWI3/p8cK3OOIHjGGBNiKcQ7yBHrs=,tag:7djq2/cCo2ooU+IwKBC4cQ==,type:str]
    db-name: ENC[AES256_GCM,data:aF+1jM3g4oS7,iv:uLKPX/TUvm4OtJXgPs5c9RFdQ/nmQeOWFMZHihE/+RY=,tag:11WF7vdSNMLqZkZIdvbhIg==,type:str]
    db-host: ENC[AES256_GCM,data:rsC2I6rZfkAuh0Uw7Kz/3KIpobRS35jahFuP5hY=,iv:JvFx05GWJQHncWasR8ZbQb0j1ZIcZmwKgHcpIGkMVy0=,tag:rtEQ5Hx+lWMF49iI6zs1Qw==,type:str]
sops:
    age:
        - recipient: age1af6yh5snkl7a0cjhh0n8q06vh0rsnpcm4q7k0avqc3ly7s3r0ctq9ju6x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMmVEUFQ5ektDdWMxSWp1
            d1lDK1lBRDN5R0ZoS2xqbWJ4a3hSSXFjMG4wCmZxY2FhamhpNG5oSGplY1NsazR1
            SFEvTUkvMHZVQnBZSHNSbGVYZjNVa2sKLS0tIGhTNUJReEYzQXlucEcrY0FyMWZ4
            S1N0RWxISGJRcW55TmUweENMRUlTbmcK/Jwq92JAZ5rfxJWaFbbytI60PxAOKc6f
            L89l/s9UL2QIy4nfZiFdMGP1A2uuJIhYhC6D/q1RMJWD7FkGYk96zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T05:11:43Z"
    mac: ENC[AES256_GCM,data:zbiXJx9JzlcPrweJxDK6P6wJChnX6g8hm7QuFo2y+dbtWIlBo3DrsBitxyg6e8A4fQMIjS5WXt4YQSz+Uljyle3OqsOlqM2Z/EbYe5HaTJo1BNOLFySKi7hGnK0pVkyQ8ycjTSTZRSaBOaui6Iaqkar7G11LbUv+H0xgEndeIhU=,iv:UIoeHAvLC2+RnNnHFM7NrH6R0GOaukW1sDEfyOwJFo4=,tag:Gg9RgCv/dZ1zfeEtqTrFrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# Secret for admin
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-admin
    namespace: wordpress
type: Opaque
stringData:
    wordpress-username: ENC[AES256_GCM,data:mo+hr28=,iv:ixlNAghNiVNY8D7HS9SIcVCIvYkt07mdXHDSJHdGml4=,tag:eG+uEzwJ0/877xbZIr70Ag==,type:str]
    wordpress-password: ENC[AES256_GCM,data:o92OMiEkK8K6FaAUZzkQIg==,iv:61t4ucHhKEHFdwrrKILmfNinEgCOJCE89Ca7YN79J9c=,tag:LLWWJYvfd+NK4a1E4jpA2g==,type:str]
    wordpress-email: ENC[AES256_GCM,data:8xqqzHLIcXmJmLLoXbctcpE=,iv:rlioX56cqea19qlDP3JnyNfYitRtYzy/2FXvYVtpJDY=,tag:I2GeyYUVElFIlSC0/iibHg==,type:str]
sops:
    age:
        - recipient: age1af6yh5snkl7a0cjhh0n8q06vh0rsnpcm4q7k0avqc3ly7s3r0ctq9ju6x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMmVEUFQ5ektDdWMxSWp1
            d1lDK1lBRDN5R0ZoS2xqbWJ4a3hSSXFjMG4wCmZxY2FhamhpNG5oSGplY1NsazR1
            SFEvTUkvMHZVQnBZSHNSbGVYZjNVa2sKLS0tIGhTNUJReEYzQXlucEcrY0FyMWZ4
            S1N0RWxISGJRcW55TmUweENMRUlTbmcK/Jwq92JAZ5rfxJWaFbbytI60PxAOKc6f
            L89l/s9UL2QIy4nfZiFdMGP1A2uuJIhYhC6D/q1RMJWD7FkGYk96zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T05:11:43Z"
    mac: ENC[AES256_GCM,data:zbiXJx9JzlcPrweJxDK6P6wJChnX6g8hm7QuFo2y+dbtWIlBo3DrsBitxyg6e8A4fQMIjS5WXt4YQSz+Uljyle3OqsOlqM2Z/EbYe5HaTJo1BNOLFySKi7hGnK0pVkyQ8ycjTSTZRSaBOaui6Iaqkar7G11LbUv+H0xgEndeIhU=,iv:UIoeHAvLC2+RnNnHFM7NrH6R0GOaukW1sDEfyOwJFo4=,tag:Gg9RgCv/dZ1zfeEtqTrFrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
