apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:1VfP6lCCRg==,iv:vAcH2p1sauhihZ41niV5RHJhRx/YRelJXCN0wMWd5RQ=,tag:Hc/beEkPltcRpUYKDplFgQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:BZhf+paYfIAl2RawGXp0,iv:gespa4h3fG/djqH21R5ehmSY9YSrIS2aNFrbXKg0xjg=,tag:xN3BsE7Ksjls7eC+RwYqDQ==,type:str]
    db-name: ENC[AES256_GCM,data:2dUzo/OGcneI,iv:h2sPLVsDWJJ7FUNm+kyKEu7RqtYAhwHGPxLL14HVp4c=,tag:kbqdxYWZpI4nRQDk1FdCRA==,type:str]
    db-host: ENC[AES256_GCM,data:c9q6WElsMpOYpdoTh/w4uv9BkWgIEMXMlSxAtRE=,iv:Gm/jzJLC3ZNZTAYdGPCqaCSTqDndsq4CCEpjdY71T8g=,tag:RIpnga04x02n3UEAxPs8Iw==,type:str]
sops:
    age:
        - recipient: age1qsdrx2wevndgmhz3aev76k7gusa2fwvu0lkrvwef2y37cc0epstsm48qa9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaGR6bUFMSXV2eUovNktR
            dGFqTTRUQlJDNythZmdXQkZ6a1hHVW1kc2tnCmpkYWVHeEZVY0gzd0hXOFlNb1Fv
            RjlDRkplZlhCNGpJdXA4UWF3Z3J2dEkKLS0tIENaOWFvcExlQmhYdkFCbXR1WlRC
            Y2lrMXNPQVVnbzlZeEJLOWs0R3NCMHMKAKeVVju+Zb85fMVzf380R9LTPa+L2e8P
            4zOUggtTGcRQo+H+sBHKLxqsrKS0sG3gK/RknhvH6ssgXt/cj1uvCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T08:56:17Z"
    mac: ENC[AES256_GCM,data:U9eSk+Ab7Qczd5K5Qb9pwCuZ+klBWZr4zqwyvl0WDAz4ISFQBvI9e33q66SjkYpx82Ad1wk+vqq9WLi/uk4r9Bj4sUEqOpFap7Kw5o8lR4QndbuOsBAFhE0SEaBX9jXYpGWX7hWG2yuOk2fAV4/D/IfIGpuRcFI7rP8qCmISK6Q=,iv:3vtomedvoDahUXcGv1sGSZaOnxb2djHj2z3a1W0Iqxs=,tag:8JWHqlRpsFp4U+48eaAHpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-admin
    namespace: wordpress
type: Opaque
stringData:
    wordpress-username: ENC[AES256_GCM,data:hptn/eA=,iv:3Qww6ppx1QdS6cSqhFTlV79kqDlHfZm1L9dtHNsg8iQ=,tag:vtSecnjulLw/iMMjdYhT6w==,type:str]
    wordpress-password: ENC[AES256_GCM,data:uLzOY8p4D3Txl0WTPO8+,iv:GBDkx/VpXWg9sttm1TAK4tOIalGs5h0lRLWNlbhyR30=,tag:rEH6Bxxd4EkkHVZyJvjing==,type:str]
    wordpress-email: ENC[AES256_GCM,data:ygR3cBjBX2AklAcQuI0vfrA=,iv:/p6Vqyj+LczZnRHlu7YtkdaMIcAz+W6MP5IPbw0hEcs=,tag:I87UkOwtd3LwFWIPGpjNyw==,type:str]
sops:
    age:
        - recipient: age1qsdrx2wevndgmhz3aev76k7gusa2fwvu0lkrvwef2y37cc0epstsm48qa9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaGR6bUFMSXV2eUovNktR
            dGFqTTRUQlJDNythZmdXQkZ6a1hHVW1kc2tnCmpkYWVHeEZVY0gzd0hXOFlNb1Fv
            RjlDRkplZlhCNGpJdXA4UWF3Z3J2dEkKLS0tIENaOWFvcExlQmhYdkFCbXR1WlRC
            Y2lrMXNPQVVnbzlZeEJLOWs0R3NCMHMKAKeVVju+Zb85fMVzf380R9LTPa+L2e8P
            4zOUggtTGcRQo+H+sBHKLxqsrKS0sG3gK/RknhvH6ssgXt/cj1uvCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T08:56:17Z"
    mac: ENC[AES256_GCM,data:U9eSk+Ab7Qczd5K5Qb9pwCuZ+klBWZr4zqwyvl0WDAz4ISFQBvI9e33q66SjkYpx82Ad1wk+vqq9WLi/uk4r9Bj4sUEqOpFap7Kw5o8lR4QndbuOsBAFhE0SEaBX9jXYpGWX7hWG2yuOk2fAV4/D/IfIGpuRcFI7rP8qCmISK6Q=,iv:3vtomedvoDahUXcGv1sGSZaOnxb2djHj2z3a1W0Iqxs=,tag:8JWHqlRpsFp4U+48eaAHpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
