apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:VT8D2aMQJg==,iv:DyKuz4ET1jZdiFAcgtIcGi9HFuaxZCichCVY7zoFXcI=,tag:Xq6So/RLCI9nuy1BvrzmHA==,type:str]
    db-password: ENC[AES256_GCM,data:+azHbPeS3iiQTr45feMe,iv:sCEd2pI5OrQmpG0QOqzoFX+NeOnbokXbsqiiRdimOX4=,tag:Y9HQzG/KYSpAnYUYZEIaBA==,type:str]
    db-name: ENC[AES256_GCM,data:8lwuaixL8Hj+,iv:1ydf7bRRxUb6zyOqTtbh8Za054uhyoP99KdK0k6PtsQ=,tag:jxGaFFpvuuI5tGf9Keo0hw==,type:str]
    db-host: ENC[AES256_GCM,data:UIdWIFKiUmXNu6j/8SW7JkIvstaAnDC0PK8Li28=,iv:SkrPv7PYgO2SyUIr/7Q1Kj0KsIQpu0vSK9fOKyH2YT8=,tag:6Iqc7gpJ589GG0ZrJ0j2VQ==,type:str]
sops:
    age:
        - recipient: age1qsdrx2wevndgmhz3aev76k7gusa2fwvu0lkrvwef2y37cc0epstsm48qa9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cDhZNDR6ZmJEMlRjSDZD
            UXdpQTN1bmRadEJQdEhiMjBMYnlnK1ByS1FjCkRQeS9YdGIvWElwdUNqaW5uY0N1
            NTE2VjZmTkdBZGtlbG0veExiZzFwaG8KLS0tIGZnUDh2OHJPT3FkWUtpQVJJNU9V
            aXpEcnc2eWNGUldEeHY5Smo1cXpuRVUK3SK9IW2OnhPr9yJJ5Qn3AYH8XPp2/h8Y
            TJyL4XQzTpLKWmRBQ08Tg+WsKr4vr5b0lV2OsBFjASs86ikz6q5x2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T06:35:40Z"
    mac: ENC[AES256_GCM,data:qvdcrXNRAYoSSqXgkLFhM547CdRpGCTWdyFYsv/ALUt8pKd4GhgmZgRZ0RDW4YcO9ZcLeAGFjv713kbxhX1mRzLEjyhR6pBF1sVHgcZWgoxA5XJLuMwonl+Hqro/6xj9aEkmaZJYTOnpOnKMZYC6MXRT+yM97UcFYMGvQo6g1lc=,iv:ZhWkB3z+Tl7lgSru8TDbM8rf+b3z5Bb7XkMNOm3Ga7M=,tag:XvHnqEpWOL7+Cf+WTtP8hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-admin
    namespace: wordpress
type: Opaque
stringData:
    wordpress-username: ENC[AES256_GCM,data:EuB7uT4=,iv:e9hE361gt33sWix+ajJaQdo7sEvkcbeQGSgcgLd2pL0=,tag:VWgtjNxb1GrXOEj2g1J41w==,type:str]
    wordpress-password: ENC[AES256_GCM,data:GBcULO+2faWjqPTtbHBD,iv:ZNYvzPOsj5zzSvHOnmw77eAefwJYtU8dRv6O4NQ8X0s=,tag:oOp8PRzKlk97iq5ACOHv7g==,type:str]
    wordpress-email: ENC[AES256_GCM,data:nUCq2B2qeLS2GHW0r3ra3A4=,iv:OOd7j1oM9cXn52Fie/hXO/n9gmZyANZ5PX2le3FTPpo=,tag:++tcu4LwH4Ej5exIXj6pDg==,type:str]
sops:
    age:
        - recipient: age1qsdrx2wevndgmhz3aev76k7gusa2fwvu0lkrvwef2y37cc0epstsm48qa9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cDhZNDR6ZmJEMlRjSDZD
            UXdpQTN1bmRadEJQdEhiMjBMYnlnK1ByS1FjCkRQeS9YdGIvWElwdUNqaW5uY0N1
            NTE2VjZmTkdBZGtlbG0veExiZzFwaG8KLS0tIGZnUDh2OHJPT3FkWUtpQVJJNU9V
            aXpEcnc2eWNGUldEeHY5Smo1cXpuRVUK3SK9IW2OnhPr9yJJ5Qn3AYH8XPp2/h8Y
            TJyL4XQzTpLKWmRBQ08Tg+WsKr4vr5b0lV2OsBFjASs86ikz6q5x2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T06:35:40Z"
    mac: ENC[AES256_GCM,data:qvdcrXNRAYoSSqXgkLFhM547CdRpGCTWdyFYsv/ALUt8pKd4GhgmZgRZ0RDW4YcO9ZcLeAGFjv713kbxhX1mRzLEjyhR6pBF1sVHgcZWgoxA5XJLuMwonl+Hqro/6xj9aEkmaZJYTOnpOnKMZYC6MXRT+yM97UcFYMGvQo6g1lc=,iv:ZhWkB3z+Tl7lgSru8TDbM8rf+b3z5Bb7XkMNOm3Ga7M=,tag:XvHnqEpWOL7+Cf+WTtP8hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
