apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:/8kCdxWQ95fzmr9dOx6hdw==,iv:ojaRFfk2YJuS7qUbZqUQbXra567ABxzVgdAntz6h8ao=,tag:bXH0MqH1Q8KQvI5DqFIVmg==,type:str]
    mysql-password: ENC[AES256_GCM,data:+ggk2IhMK35k21g1Jxq/,iv:uAVV/H+e4/t/7PtcFWa4hjqCt3s53sPkVS6iZdCVIKs=,tag:W4sBK0wufRmnxLxJnRc9FA==,type:str]
sops:
    age:
        - recipient: age1hm04zjpw529fpy88780sn786tat7xvkj9ek7v47fyr0mcwzpsyksvyjazz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTm1vejdhZlQ5Q1RlL2dy
            d2x4clNvKzZLZVJSeGg1T1dPWTJ3bUNIQUZ3CkMrckNkM1h5clRlV29CQWIwVXBh
            U3dmTDNPa2ROZnBYV2NLajNvVU85Z0UKLS0tIDR3UXduQWpnQ3pNZFNJMmNKNWlp
            N09mbUFXK0lkV09RWHZlV0R3bjBYcDgKBuKyJZqirAASKLq7d9nghJRsatM1R9Cs
            BR9CiiiTChu9TPh3Nw7tmYGAZdRTojRl/CzHGpdu4bbQ9vYuW7WcmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T12:16:48Z"
    mac: ENC[AES256_GCM,data:22HSJDpnaFrDTCEzun0J99/4cPcstaQXzv9VNY5WeLwQS7IDgJ5eUaY18niTgKvjAnvbpiti5VB10ttYe9lVD4UV9Tt//ixtaavKo+2i/jrkuonqF0EN8OpFreN3laibynCrHjXYHm5dYoqpSEhjQ4p6nLLIhzgEVBJxgK3FXuk=,iv:gp+OgqY872lgxVZ3V0kQZJ5azKNyf2bBYjYhK/kTKdI=,tag:aMSiBu9zRg6gBMszsBIUmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
