apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:1eh7/u1I+BVN3IBTkUNrlA==,iv:C9hesM2yC0JxPjUAuYry+NZ4/bI5jWt4NHwiT/H8vpA=,tag:+qEIFAm67WTkCRwfOUY6Jw==,type:str]
    mysql-password: ENC[AES256_GCM,data:IeHNIkOuZmYJL3H4aWE4,iv:L8zy+v/nI4hsP1A4ZdEvnnEGgt7oco3f6+Yg4BcxJqo=,tag:xs6nsESpfnmacNAL/yF6vg==,type:str]
sops:
    age:
        - recipient: age1qsdrx2wevndgmhz3aev76k7gusa2fwvu0lkrvwef2y37cc0epstsm48qa9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV05wejJNMmpEUWFRRWdW
            NkxwN0FnS1oxNlhmRCtXMXBNNHZRS3RCRkI4CjhQNllIUitTcFZsR2hGZVp4ZDJW
            UDdvRDJoWVYrTFlPbWFlbHYzQ3hqQkUKLS0tIENhdGlTREQwOU8wNUFqU2srcFVL
            Mk8zWmlySUsyb3puMkhmRTgyWWhnbUUKIYvpb0hohQD5bVHvJGyXxEo/P1Snm1lu
            5a3g1+FKyA0fQYLdsxBEyciKYv5zYowZB4FxUXt5MdQkLUlOH5PqFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T08:40:15Z"
    mac: ENC[AES256_GCM,data:bBgfee8Zb/pImjWbAaLlTdWHWWtooSeTlY+Eb6nguvUaGwWGqJsETnAihNO47znGCGYbOVsLGDG9U5290xsyDTTbA4VzTYin+KRJVnAaDCLDh+hosklmsae/BeUBfgllyiqgaHnneRJazjNVJ33PFWv0Ko9xgI3zdgumVVy41lg=,iv:YaA9+g52PXXAu6Pg+auNqbO5rss8UlOsqoIvfnFQQyU=,tag:1ZlWcG4YlhzkGoMzH9AkAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
