apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:hbVM0SEEWABVTFi8aaVjz8s=,iv:LIuWs+MGMbO3ojhbkkwERo7M8/Ddd1dwZK6yJ9g0MCc=,tag:NnUOVCc0uX1dYo3FSAkpzA==,type:str]
sops:
    age:
        - recipient: age1af6yh5snkl7a0cjhh0n8q06vh0rsnpcm4q7k0avqc3ly7s3r0ctq9ju6x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaGdiZE9HcndvMytVdzVP
            dFN6dDFBc3JnbGhYMnNkVHl4Sko4Zm1GTVFFCkoxSkFSN0ZrNXRHSVRuZVZwRng5
            d0pGUkxuTWZiak4zTEEvcnFhM2hjVHMKLS0tIERsZjhnSU9FT3pPVjZpTVZwUmpO
            WSttVm02MVFWeTV6UTVsb0p5ZDZHUncK7Z2aNsgOT7B8ljBIJ82sTxr4jmiC5MSJ
            rxmEENMRj2iUwZNmtGVbLXWfVPOTjcIXz7i84umYo9BfvMb5k6IZOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T05:11:31Z"
    mac: ENC[AES256_GCM,data:MVK0x3ANBycqD8jA8ZKAbScOjYJq4pIVpLdL+mOkoWdmSrQp4AaeHQjieQwOvADf0yYSZClZgE8uFsm96vRKx/PzIPZpWxr5OywLGVpuLsi4YoCuaitYeBIhJ3NmTNbExKaFehdRs8x0xBXR63ZSBl+1n4BB7BTGbe1sMkdt9II=,iv:m3SUTnMFFpRMG0KJiNhsYRSaAUviGMSx5QOfbQq3D2s=,tag:7KkSSrWQdLOjJPqbWLQ4SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
