apiVersion: v1
kind: Secret
metadata:
    name: mysql-auth
    namespace: mysql
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:fpAmfTPOvqvLxBhpcjOB/vA=,iv:CiEOivaBpXFQFn0lulDfDgFP4t9TLN/iJQ4QagCq3kE=,tag:sLqwisLZ7s/vqGFegJ5/fw==,type:str]
    mysql-password: ENC[AES256_GCM,data:g1PIaYV1/TA/97FxdfJe6A==,iv:kuW75WtVO9EK/ywDdtZCSdiHey7hspay/zVYe1/KZYk=,tag:/3oV8696IuKf32l+Gi6Mmg==,type:str]
sops:
    age:
        - recipient: age1af6yh5snkl7a0cjhh0n8q06vh0rsnpcm4q7k0avqc3ly7s3r0ctq9ju6x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwakZpTVRnRFFReEtlVFUz
            Smt5Q3NyQzBZRUh4eHBBQmpZWE5RYmtMcTJ3CjhISEFiOGRhZG1QV3JxYWZ5RjYy
            blFUeUM3UkRRN1Nuc2llNEQvTzRGd1kKLS0tIGpQSFZBbWJLdU1EN2IrcDBkelo4
            Ymc2NEZNSi9iNVliRUZ0MXBueXMwajgKBUkg3ETmVKSLQSjSW0ut0FUA/6O+AqWr
            rI6Xo/tGHdXv5oevcIPuSzhE+ebZFqMy8OsuUchuf8bJalAf37Jw4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T06:52:11Z"
    mac: ENC[AES256_GCM,data:+PbmkFKjLIKX94u3L1symUECMgEfxH/Ow+cH1nvzHPEcW1sR+hpGII/LsVkvaUcRVXWdfepVDUtFq9oXTNnhrl5SmmYevk9zC4DZ215nCT0rH+u0f0MJ87qrBUwyjWT9NPwAndpjn20+kvcQVh+hG6NKcyZjtl7w0glyn71F2MA=,iv:DBLuRunF0U4eixlYcz6Jgd+8jsfERDqieruRaqRRiEE=,tag:GMxeF+K1HeJmO0LAiR3UVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
